apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
spec:
  gateways:
    - bookinfo-gateway
  hosts:
  - '*'
  http:
    - match:
      - uri:
          exact: /kiali
      route:
      - destination:
          host: kiali.istio-system.svc.cluster.local
          port:
            number: 20001

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kiali
spec:
  host: kiali.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL