apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 49.232.71.52
      - 49.232.68.241